foreground   #dee9f1
background   #1e2b12
cursor       #dee9f1

color0       #1e2b12
color8       #9ba3a8
color1       #5CADFA
color9       #5CADFA
color2       #44C6CC
color10      #44C6CC
color3       #68E0E8
color11      #68E0E8
color4       #A5C3A9
color12      #A5C3A9
color5       #92B9FB
color13      #92B9FB
color6       #9FE2EB
color14      #9FE2EB
color7       #dee9f1
color15      #dee9f1
