--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/user/Pictures/Wallpapers/pexels-asadphoto-1450360.jpg"

-- Special
background="#1e2b12"
foreground="#dee9f1"
cursor="#dee9f1"

-- Colors
color0="#1e2b12"
color1="#5CADFA"
color2="#44C6CC"
color3="#68E0E8"
color4="#A5C3A9"
color5="#92B9FB"
color6="#9FE2EB"
color7="#dee9f1"
color8="#9ba3a8"
color9="#5CADFA"
color10="#44C6CC"
color11="#68E0E8"
color12="#A5C3A9"
color13="#92B9FB"
color14="#9FE2EB"
color15="#dee9f1"
