# Shell variables
# Generated by 'wal'
wallpaper='/home/user/Pictures/Wallpapers/pexels-asadphoto-1450360.jpg'

# Special
background='#1e2b12'
foreground='#dee9f1'
cursor='#dee9f1'

# Colors
color0='#1e2b12'
color1='#5CADFA'
color2='#44C6CC'
color3='#68E0E8'
color4='#A5C3A9'
color5='#92B9FB'
color6='#9FE2EB'
color7='#dee9f1'
color8='#9ba3a8'
color9='#5CADFA'
color10='#44C6CC'
color11='#68E0E8'
color12='#A5C3A9'
color13='#92B9FB'
color14='#9FE2EB'
color15='#dee9f1'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
